version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - Write-Host "Building, Testing and packaging application..."
      - mvn package -DskipTests
  post_build:
    commands:
      - Write-Host "Build completed successfully."
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
